import { chromium } from 'playwright';
const [width, path, sel, label, h] = [Number(process.argv[2]), process.argv[3], process.argv[4], process.argv[5], Number(process.argv[6]||900)];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width, height: h } });
await p.goto('http://localhost:3000' + path, { waitUntil: 'networkidle', timeout: 60000 });
await p.waitForTimeout(800);
await p.evaluate((sel) => document.querySelector(sel)?.scrollIntoView({ block: 'start' }), sel);
await p.waitForTimeout(1400);
await p.screenshot({ path: `/tmp/shots/${label}-${width}.png` });
await b.close();
console.log('ok');
